# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/mt6765-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter camellia everpal light,$(TARGET_DEVICE)),)

endif
